default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  database: rails-spa-cookie-session-sample_development
  socket: /tmp/mysql.sock

development:
  <<: *default

test:
  <<: *default
  database: rails-spa-cookie-session-sample_test

staging:
  <<: *default

production:
  <<: *default

